### ISSUE TITLE
Automatically grab setup information of ODS

### ISSUE THREAD

**Issue by jorge-romero** [opendevstack/ods-e2e-tests#2]
To avoid setting the environment variables manually we need to grab the information from the config of ODS.

The current way of provide the parameters needed to run the tests could be mantained so it won't be needed to have the configuration in the machine that will run the tests and can be injected.

**Comment by clemensutschig** [comment]
Usually the repo here would sit Side by side with ods-configuration.. so a Quick Check if its there and then you can use the environment .. 

All User credentials needed.. should sit in a Second file.. that is git-ignored..

@michaelsauter fyi

**Comment by jorge-romero** [comment]
Added code to load and override the environment setup from:
1. ods-configuration/ods-core.env
2. .env -> It should contain the passwords and other needed information. I can override the ods-core.env environment or it will be the first source if the tests are executed in a computer that does not have the ods-configuration folder.
3. The envioroment variables, that will override the previous ones as the last place to setup the tests.

The code is included in the PR #3
